use_frameworks!

platform :ios, '10.0'

target 'SwiftyVideoTool_Example' do
  pod 'SwiftyVideoTool', :path => '../'
  pod 'SnapKit'
  pod 'JFPopup'

   post_install do |installer|
      installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CODE_SIGN_IDENTITY'] = ''
             end
        end
      end
    end

  target 'SwiftyVideoTool_Tests' do
    inherit! :search_paths

    
  end
end
